symlink_command: stow . --target="$HOME" --no-folding

packages:
  apt:
    - tmux
    - stow
    - git

  pip:
    - thefuck
    - tmuxp
    - gdtoolkit==4.*

  snap:
    - nvim
    - btop
    - yq

  deb:
    - name: sharkdp/bat
      command: bat
      file: 'bat_<version>_amd64.deb'
    - name: dandavison/delta
      command: delta
      file: 'git-delta_<version>_amd64.deb'
    - name: BurntSushi/ripgrep
      command: rg
      file: 'ripgrep_<version>-1_amd64.deb'

  manual_downloads:
    - name: Godot
      link: https://godotengine.org/
    - name: JetBrainsMono Nerd Font
      link: https://www.nerdfonts.com/font-downloads
    - name: Aseprite
      link: https://www.aseprite.org/
    - name: catppuccin/aseprite
      link: https://github.com/catppuccin/aseprite
    - name: catppuccin/godot
      link: https://github.com/catppuccin/godot
    - name: catppuccin/windows-terminal
      link: https://github.com/catppuccin/windows-terminal

  self_managed:
    - name: ohmyzsh
      install_cmd: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      update_cmd: |
        omz update | cat
    - name: tpm
      install_cmd: |
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        ~/.tmux/plugins/tpm/bin/install_plugins all
      update_cmd: |
        ~/.tmux/plugins/tpm/bin/update_plugins all

  git_repositories:
    - name: fzf
      path: ~/.fzf
      custom_clone: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      post_cmd: |
        ~/.fzf/install --key-bindings --completion --no-update-rc
    - name: fzf-tab
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/fzf-tab
      url: https://github.com/Aloxaf/fzf-tab
    - name: zsh-completions
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-completions
      url: https://github.com/zsh-users/zsh-completions
    - name: zsh-syntax-highlighting
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
      url: https://github.com/zsh-users/zsh-syntax-highlighting.git
    - name: zsh-autosuggestions
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
      url: https://github.com/zsh-users/zsh-autosuggestions

  git_file_downloads:
    - name: ajeetdsouza/zoxide
      type: release
      cmd: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/v"$latest_version"/install.sh | sh
    - name: catppuccin/zsh-syntax-highlighting
      type: commit
      cmd: |
        rm "$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"
        wget --no-verbose -P "$HOME/.zsh/" https://github.com/catppuccin/zsh-syntax-highlighting/raw/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh
    - name: catppuccin/bat
      type: commit
      cmd: |
        rm "$(bat --config-dir)/themes/Catppuccin Mocha.tmTheme"
        wget --no-verbose -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme
        bat cache --build
    - name: catppuccin/delta
      type: commit
      cmd: |
        rm "$HOME/.config/delta/themes/catppuccin.gitconfig"
        wget --no-verbose -P "$HOME/.config/delta/themes" https://github.com/catppuccin/delta/raw/main/catppuccin.gitconfig
    - name: catppuccin/btop
      type: release
      cmd: |
        wget --no-verbose -qO- https://github.com/catppuccin/btop/releases/download/"$latest_version"/themes.tar.gz | tar -xzv -C "$XDG_CONFIG_HOME/btop/themes" --strip-components=1
