symlink_command: stow . --target="$HOME" --no-folding

packages:
  pacman:
    - alacritty
    - archlinux-xdg-menu
    - bat
    - bc
    - btop
    - dunst
    - egl-wayland
    - fd
    - fzf
    - git
    - git-delta
    - go-yq
    - hypridle
    - hyprland
    - hyprlock
    - hyprpaper
    - just
    - neovim
    - python-pipx
    - ripgrep
    - rofi
    - stow
    - tmux
    - tmuxp
    - waybar
    - xcur2png
    - xdg-desktop-portal-hyprland
    - zoxide
    - flameshot
    - grim
    - slurp

  yay:
    - lefthook

  pipx:
    - gdtoolkit==4.*

  manual_downloads:
    - name: Godot
      link: https://godotengine.org/
    - name: JetBrainsMono Nerd Font
      link: https://www.nerdfonts.com/font-downloads
    - name: Aseprite
      link: https://www.aseprite.org/
    - name: catppuccin/aseprite
      link: https://github.com/catppuccin/aseprite
    - name: catppuccin/godot
      link: https://github.com/catppuccin/godot

  self_managed:
    - name: tpm
      install_cmd: |
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm &&
        ~/.tmux/plugins/tpm/bin/install_plugins all
      update_cmd: "~/.tmux/plugins/tpm/bin/update_plugins all"
    - name: ohmyzsh
      install_cmd: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
      update_cmd: "local result=$(omz update) && echo $result"

  git_repositories:
    - name: fzf-tab
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/fzf-tab
      url: https://github.com/Aloxaf/fzf-tab
    - name: zsh-completions
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-completions
      url: https://github.com/zsh-users/zsh-completions
    - name: zsh-syntax-highlighting
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
      url: https://github.com/zsh-users/zsh-syntax-highlighting.git
    - name: zsh-autosuggestions
      path: |
        "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
      url: https://github.com/zsh-users/zsh-autosuggestions

  git_file_downloads:
    - name: catppuccin/zsh-syntax-highlighting
      type: commit
      cmd: |
        rm "$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh" &&
        wget --no-verbose -P "$HOME/.zsh/" https://github.com/catppuccin/zsh-syntax-highlighting/raw/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh
    - name: catppuccin/bat
      type: commit
      cmd: |
        rm "$(bat --config-dir)/themes/Catppuccin Mocha.tmTheme" &&
        wget --no-verbose -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme &&
        bat cache --build
    - name: catppuccin/delta
      type: commit
      cmd: |
        rm "$HOME/.config/delta/themes/catppuccin.gitconfig" &&
        wget --no-verbose -P "$HOME/.config/delta/themes" https://github.com/catppuccin/delta/raw/main/catppuccin.gitconfig
    - name: catppuccin/btop
      type: release
      cmd: |
        wget --no-verbose -qO- https://github.com/catppuccin/btop/releases/download/"$latest_version"/themes.tar.gz | tar -xzv -C "$XDG_CONFIG_HOME/btop/themes" --strip-components=1
