[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 2, y = 2 }

[cursor]
style = { shape = "Beam" }

[mouse]
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

[keyboard]
bindings = [
  { key = "PageUp", action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" },
  { key = "T", mods = "Control | Shift", action = "CreateNewWindow" }
]

[selection]
save_to_clipboard = true

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[colors]
draw_bold_text_with_bright_colors = true
